### ISSUE TITLE
About i-code V1 project

### ISSUE THREAD

**Issue by chengshuang18** [microsoft/i-Code#40]
A great job. Also, i would like to ask if you will open source the code of i-Code V1 project? It would be exciting if it could

**Comment by ziyi-yang** [comment]
Hi, thanks a lot for the interest in i-Code V1. Since it uses some internal Microsoft data and code base, we couldn't release the code/checkpoints. One option is to re-design and re-train the model on public datasets but that'd be a bit stretch given the team's bandwidth. We notice this makes open-sourcing difficult, and this is why we shift to public datasets and codebases in later research efforts (e.g., i-Code-Doc and V3) for publication. Sry about the inconvenience.
